## Clear workspace
rm(list = ls())
## Include library
library(roahd)
library(SDMTools)
library(R.matlab)
library(stats)
library(ica)
library(caret)
library(MVN)
library(kernlab)
source('E:/TO_upload/3.Implementation/SourceFunctions.R')
SourceFunctions()
source('E:/TO_upload/3.Implementation/fss_Algorithms.R')
Dataset<-LoadData("D1")
D1.FCBF.result<-fss_Algorithms(Dataset,Fss_Alg="FCBF")
D1.CFS.result<-fss_Algorithms(Dataset,Fss_Alg="CFS")
D1.Fisher.result<-fss_Algorithms(Dataset,Fss_Alg="Fisher")
D1.mRMRe.result<-fss_Algorithms(Dataset,Fss_Alg="mRMRe")
D1.Relief.result<-fss_Algorithms(Dataset,Fss_Alg="ReliefF")
D1.RRE.result<-fss_Algorithms(Dataset,Fss_Alg="RRE",corr.threshold=0.6)

Dataset<-LoadData("D2")
D2.FCBF.result<-fss_Algorithms(Dataset,Fss_Alg="FCBF")
D2.CFS.result<-fss_Algorithms(Dataset,Fss_Alg="CFS")
D2.Fisher.result<-fss_Algorithms(Dataset,Fss_Alg="Fisher")
D2.mRMRe.result<-fss_Algorithms(Dataset,Fss_Alg="mRMRe")
D2.Relief.result<-fss_Algorithms(Dataset,Fss_Alg="ReliefF")
D2.RRE.result<-fss_Algorithms(D2.RRE.result[[3]],Fss_Alg="RRE",corr.threshold=0.9)
Dataset<-LoadData("D3")

D3.FCBF.result<-fss_Algorithms(Dataset,Fss_Alg="FCBF")
D3.CFS.result<-fss_Algorithms(Dataset,Fss_Alg="CFS")
D3.Fisher.result<-fss_Algorithms(Dataset,Fss_Alg="Fisher")
D3.mRMRe.result<-fss_Algorithms(Dataset,Fss_Alg="mRMRe")
D3.Relief.result<-fss_Algorithms(Dataset,Fss_Alg="ReliefF")
D3.RRE.result<-fss_Algorithms(Dataset,Fss_Alg="RRE",corr.threshold=0.7)

Dataset<-LoadData("D4")
D4.FCBF.result<-fss_Algorithms(Dataset,Fss_Alg="FCBF")
D4.CFS.result<-fss_Algorithms(Dataset,Fss_Alg="CFS")
D4.Fisher.result<-fss_Algorithms(Dataset,Fss_Alg="Fisher")
D4.mRMRe.result<-fss_Algorithms(Dataset,Fss_Alg="mRMRe")
D4.Relief.result<-fss_Algorithms(Dataset,Fss_Alg="ReliefF")
D4.RRE.result<-fss_Algorithms(Dataset,Fss_Alg="RRE",corr.threshold=0.6)

Dataset<-LoadData("D5")
D5.FCBF.result<-fss_Algorithms(Dataset,Fss_Alg="FCBF")
D5.CFS.result<-fss_Algorithms(Dataset,Fss_Alg="CFS")
D5.Fisher.result<-fss_Algorithms(Dataset,Fss_Alg="Fisher")
D5.mRMRe.result<-fss_Algorithms(Dataset,Fss_Alg="mRMRe")
D5.Relief.result<-fss_Algorithms(Dataset,Fss_Alg="ReliefF")
D5.RRE.result<-fss_Algorithms(Dataset,Fss_Alg="RRE",corr.threshold=0.9)
